### ISSUE TITLE
Publish silently commits the transaction

### ISSUE THREAD

**Issue by Jonathan34** [ThreeDotsLabs/watermill#162]
See the following code.
With gorm as a wrapper and with autoinitialize schema true, the publish will commit the transaction without any explicit tx.commit().

https://goplay.space/#0YHAklO60Ns

The workaround is to precreate the schema your self and disable the flag to create it automatically...

**Comment by roblaszczak** [comment]
Hello, we are working on this issue. For now, you can set `AutoInitializeSchema` to false.

**Comment by maclav3** [comment]
https://github.com/ThreeDotsLabs/watermill-sql/pull/6 addresses this problem.

So the problem is that with MySQL, a `CREATE TABLE` always commits any ongoing transaction.
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

I don't think we're able to circumvent it, so the pull request makes `NewPublisher` return an error when `AutoInitializeSchema` is on, and the `db` handle looks like an ongoing transaction.

It's an inconvenience, but it solves the unexpected problem and prevents any surprises for the caller.
In case you want to publish messages in a manually orchestrated tx, you have to prepare your schema yourself, and vice versa – if you want to have an autogenerated schema, don't use a transaction as the db handle :(

Now things may be a bit different with Postgres, but I didn't go that deep for now.
@Jonathan34 @roblaszczak

**Comment by roblaszczak** [comment]
So probably ThreeDotsLabs/watermill-sql#6  is all that we can do here - if someone is trying to use transaction and initialize schema error will occur.
