### ISSUE TITLE
How can I pass context from publish message to subscribe, using go channel pubsub.

### ISSUE THREAD

**Issue by daiaioz** [ThreeDotsLabs/watermill#194]
What I try to solve is making Event handlers are invoked in context of the same transaction boundary. So I can rollback when event handlers fail. But I don't know how to do this. I see in code that message is copy when publish, and context is not propagated.

**Comment by m110** [comment]
Hey @daiaioz. What you're trying to do is impossible by design. When using event-driven applications, you have to accept eventual consistency or build distributed transactions.

It's true that Go channel implementation could support this kind of context passing, but any other Pub/Sub won't (how do you serialise a database transaction handle?). 

If you just need to publish events in transaction with saving some entity, you can check the "Pattern 2: Transactional Events
" here: https://threedots.tech/post/when-sql-database-makes-great-pub-sub/

**Comment by daiaioz** [comment]
@m110 thank for your answer.
