### ISSUE TITLE
Retry Middleware blocked message

### ISSUE THREAD

**Issue by guihouchang** [ThreeDotsLabs/watermill#271]
When I use a single consumer, subsequent messages cannot be consumed normally after Retry is triggered.
```
retryLoop:
		for {
			waitTime := expBackoff.NextBackOff()
			select {
			case <-ctx.Done():
				return producedMessages, err
			case <-time.After(waitTime):
				// go on
			}

			producedMessages, err = h(msg)
			if err == nil {
				return producedMessages, nil
			}

			if r.Logger != nil {
				r.Logger.Error("Error occurred, retrying", err, watermill.LogFields{
					"retry_no":     retryNum,
					"max_retries":  r.MaxRetries,
					"wait_time":    waitTime,
					"elapsed_time": expBackoff.GetElapsedTime(),
				})
			}
			if r.OnRetryHook != nil {
				r.OnRetryHook(retryNum, waitTime)
			}

			retryNum++
			if retryNum > r.MaxRetries {
				break retryLoop
			}
		}
```

**Comment by checkmunza** [comment]
Do you mean after entering `retryLoop` section?

**Comment by guihouchang** [comment]
> 

yes, when I set InitialInterval 30min, it causes message blocking

**Comment by m110** [comment]
@guihouchang if you set the initial interval to 30 minutes, the middleware waits for 30 minutes after a message processing fails. This is by design, and it blocks further messages. If you need to unblock the following messages, you need something more complex, like publishing the broken message on a poison queue.
