### ISSUE TITLE
Context not being propagated through command bus

### ISSUE THREAD

**Issue by saikapuluru99** [ThreeDotsLabs/watermill#429]
Hi all, so I am using a Command processor and Command Bus for pub sub in my server. When I do this I have some important information in the context that I want to propagate to my handlers. The message context contains that information when `OnSend` is called on the command bus, but this message context seems to be lost when `OnHandle` is called on the command processor. Is this expected?

**Comment by m110** [comment]
Hey! Yes, this is expected since your message is supposed to go over the network evetually (unless you use Go Channel Pub/Sub, but that's an exception). 

You need to implement a marshaler that transforms the context into the message (you can use the metadata, for example) and then unmarshals it back into context.
