### ISSUE TITLE
subscribe for new messages and invoke different handler based on message types

### ISSUE THREAD

**Issue by MartinForReal** [ThreeDotsLabs/watermill#64]
Router create a channel for each handler and I think it would be a good idea to subscribe new messages and invoke different handlers. because it has better performance.

**Comment by roblaszczak** [comment]
This is a design choice. When we are receiving messages in some Pub/Subs we want to keep messages in order (for examples in Kafka). And because of it, we cannot spawn multiple subscriptions. And it is up to subscriber implementation to deliver more messages when order is not mandatory (like Google Cloud Pub/Sub for example).
